FROM mcr.microsoft.com/devcontainers/python:3.10-bookworm

ENV POETRY_VERSION=1.8.4
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/home/vscode/.cache/pypoetry
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

ENV PATH="${PATH}:${POETRY_VENV}/bin"

RUN mkdir -p /home/vscode/.cache/pypoetry

WORKDIR /workspace

COPY poetry.lock pyproject.toml ./
RUN poetry install --no-interaction --no-cache \
    && chown -R vscode:vscode /home/vscode/.cache /workspace/.venv

USER vscode
