"""Fixed current Models to modern style

Revision ID: 24398b8baa46
Revises: e9cd2688254f
Create Date: 2026-01-13 13:29:33.692463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24398b8baa46'
down_revision: Union[str, Sequence[str], None] = 'e9cd2688254f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('muflons', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('muflons', 'size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('users_tg_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_unique_constraint(op.f('users_tg_id_key'), 'users', ['tg_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('muflons', 'size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('muflons', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
